name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1.4.2
      with:
        java-version: '15'
    - uses: coursier/cache-action@v4.1
    - name: install sbt
      run: curl -Ls https://git.io/sbt > ./sbt && chmod 0755 ./sbt
    - name: test
      run: ./sbt -v -J--enable-preview scalafmtCheckAll scalafmtSbtCheck +test
