name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v6
      with:
        java-version: openjdk@1.14
    - name: test
      run: sbt -v -J--enable-preview scalafmtCheckAll scalafmtSbtCheck +test
