name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [15, 16]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: coursier/cache-action@v6
    - name: install sbt
      run: curl -Ls https://git.io/sbt > ./sbt && chmod 0755 ./sbt
    - name: test
      run: ./sbt -v -J--enable-preview scalafmtCheckAll scalafmtSbtCheck +test
