name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [15, 16, 17]
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        check-latest: true
        distribution: adopt
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - name: test
      run: sbt -v "+scalafmtCheckAll" scalafmtSbtCheck +test
